{% set version = "42e4602dd06a36282b16123e7f587c08f397b272" %}

package:
  name: pyrtools
  version: master

source:
  - git_url: https://github.com/LabForComputationalVision/matlabPyrTools
    git_rev: {{ version }}
    folder: src

  - path: mex_compile.m

build:
  number: 0
#  noarch: generic
#  binary_relocation: False
#  ignore_prefix_files: True

  script_env:
  - MATLAB_ROOT_DIR


#test:
#  script_env:
#  - MATLAB_ROOT_DIR

about:
  home: http://www.cns.nyu.edu/~eero/steerpyr
  license: MIT License
  summary:
    Matlab tools for multi-scale image processing, including Laplacian pyramids,
    Wavelets, and Steerable Pyramids.

  