{% set version = "master" %}

package:
  name: matnapack
  version: {{ version }}

source:
  - git_url: https://github.com/gagphil1/matnapack.git
#    git_rev: v{{ version }}


build:
  number: 0
  noarch: generic

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/ewiger/matnapack
  license: MIT
  summary:
    Packing a set of .m MATLAB files from the global namespace into +somenamespace folder
  description:
    Packing a set of .m MATLAB files from the global namespace into +somenamespace folder. Packing procedure will
    also include step on injecting the 'import somenamespace.*' statement into every modified function. Project
    acts as a kind of compiler for putting matlab code into namespace scope.

  