{% set version = "master" %}

package:
  name: matlabfns
  version: {{ version }}

source:
  - git_url: https://github.com/gagphil1/PeterKovesiImage.git
#    git_rev: v{{ version }}

build:
  number: 7
  noarch: generic

requirements:
  build:
  - matlab_support

  run:
  - matlab_support

about:
  home: http://www.peterkovesi.com/matlabfns/index.html
  license: simplified BSD License
  license_family: BSD
  summary:
    Peter Kovesi's functions for image processing.

  