{% set version = "42e4602dd06a36282b16123e7f587c08f397b272" %}

package:
  name: pyrtools
  version: {{ version }}

source:
  - git_url: https://github.com/LabForComputationalVision/matlabPyrTools
    git_rev: {{ version }}
    folder: src

  - path: mex_compile.m

build:
  number: 0
#  noarch: generic
#  binary_relocation: False
#  ignore_prefix_files: True

  script_env:
  - MATLAB_ROOT_DIR

requirements:
  build:
  - matlab_support

  run:
  - matlab_support


about:
  home: http://opencv.org/
  license: BSD 3-clause
  license_family: BSD
  summary: Computer vision and machine learning software library.
  description: |
    OpenCV (Open Source Computer Vision Library) includes several hundreds of computer vision algorithms.
    It has a modular structure,which means that the package includes several shared or static libraries.
  doc_url: http://docs.opencv.org/
  doc_source_url: https://github.com/opencv/opencv/tree/master/doc

  